allowBuilds:
  '@parcel/watcher': true
  '@shopify/react-native-skia': true
  msgpackr-extract: true
  unrs-resolver: true
  vd-tool: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@shopify/react-native-skia"
  - msgpackr-extract
  - unrs-resolver
  - vd-tool